### ISSUE TITLE
Time-out on searching Thermostats

### ISSUE THREAD

**Issue by WimHe** [ralfvd/nl.bevlogenheid.evohome#26]
The problem with adding thermostats still seems to be there.
App version 2.1.9, Homey 2.1.0 i still get 30000millisecond time-out on searching for the (10) thermostats.
restart, re-install did not resolve it.
report :
3bff097c-a702-42aa-bea8-b096cbe2d2f1

**Comment by ralfvd** [comment]
Wim,

In the logging, I see this, immediately from the start:

{ error: 'attempt_limit_exceeded’ }

This means that the Evohome cloud is refusing login from the Homey client due to too many login attempts. This is not only from Homey, but also from other devices that might be trying to access the Evohome cloud with your account details.

Do you have other automation systems running that are logging into Evohome/Honeywell ?  

Please disable the app for e.g. 15 minutes and then restart the app.  And then resubmit the logging. Maybe there is a difference then.





On 3 April 2019 at 20:57:32, Wim van den Heuvel (notifications@github.com) wrote:

The problem with adding thermostats still seems to be there.
App version 2.1.9, Homey 2.1.0 i still get 30000millisecond time-out on searching for the (10) thermostats.
report :
3bff097c-a702-42aa-bea8-b096cbe2d2f1

**Comment by WimHe** [comment]
Great thanks for the quick reply, it is solved. I am moving all my functionality from Homey to Homey Pro. So the old Homey was the other device logged into the Honeywell cloud. After removing it i can now get the devices in my new Homey Pro.
Solved.
